version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    depends_on:
      - php
    volumes:
      - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./xls-exchanger:/var/www/xls-exchanger
      - ./tmp/json:/tmp/json
      - ./tmp/xls:/tmp/xls
      - ./tmp/logs:/tmp/logs

  php:
    container_name: php
    build: ./docker/images/php
    restart: always
    volumes:
      - ./xls-exchanger:/var/www/xls-exchanger
      - ./tmp/json:/tmp/json
      - ./tmp/xls:/tmp/xls
      - ./tmp/logs:/tmp/logs